// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package hr.as2.inf.server.requesthandlers.rmi;

public final class AS2ServerRequestHandlerRmi_Stub
    extends java.rmi.server.RemoteStub
    implements hr.as2.inf.common.requesthandlers.rmi.AS2RequestHandlerAS2RecordRmi, hr.as2.inf.common.requesthandlers.rmi.AS2RequestHandlerHashtableRmi, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_serviceAS2Record_0;
    private static java.lang.reflect.Method $method_serviceHashtable_1;
    
    static {
	try {
	    $method_serviceAS2Record_0 = hr.as2.inf.common.requesthandlers.rmi.AS2RequestHandlerAS2RecordRmi.class.getMethod("serviceAS2Record", new java.lang.Class[] {hr.as2.inf.common.data.AS2Record.class});
	    $method_serviceHashtable_1 = hr.as2.inf.common.requesthandlers.rmi.AS2RequestHandlerHashtableRmi.class.getMethod("serviceHashtable", new java.lang.Class[] {java.util.Hashtable.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public AS2ServerRequestHandlerRmi_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of serviceAS2Record(AS2Record)
    public java.lang.Object serviceAS2Record(hr.as2.inf.common.data.AS2Record $param_AS2Record_1)
	throws hr.as2.inf.common.exceptions.AS2Exception, java.lang.Exception, java.rmi.RemoteException
    {
	Object $result = ref.invoke(this, $method_serviceAS2Record_0, new java.lang.Object[] {$param_AS2Record_1}, -7428392481148580017L);
	return ((java.lang.Object) $result);
    }
    
    // implementation of serviceHashtable(Hashtable)
    public java.lang.Object serviceHashtable(java.util.Hashtable $param_Hashtable_1)
	throws java.lang.Exception, java.rmi.RemoteException
    {
	Object $result = ref.invoke(this, $method_serviceHashtable_1, new java.lang.Object[] {$param_Hashtable_1}, -3403305768928437566L);
	return ((java.lang.Object) $result);
    }
}
